// Explicit icon map so only the icons we actually use get bundled.
// (A namespace `import * as` from lucide-react pulls in the entire icon set,
// ~600kB, which defeats the whole "lean" pitch.)
import {
  GitBranch,
  Package,
  RefreshCw,
  GitPullRequest,
  Database,
  LayoutGrid,
  Boxes,
  Clock,
  Lock,
  KeyRound,
  Users,
  ShieldCheck,
  ScrollText,
  Activity,
  HeartPulse,
  Gauge,
  TerminalSquare,
  SquareTerminal,
  Bot,
  Save,
  Server,
  Network,
  Hammer,
  CloudUpload,
  Box,
  type LucideIcon,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  GitBranch,
  Package,
  RefreshCw,
  GitPullRequest,
  Database,
  LayoutGrid,
  Boxes,
  Clock,
  Lock,
  KeyRound,
  Users,
  ShieldCheck,
  ScrollText,
  Activity,
  HeartPulse,
  Gauge,
  TerminalSquare,
  SquareTerminal,
  Bot,
  Save,
  Server,
  Network,
  Hammer,
  CloudUpload,
};

export const FallbackIcon = Box;
